module.exports = {
   debug: true /* True means visible browser, false unvisible */,
   lang: 'en' /* Log's language in console */,
   userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:70.0) Gecko/20100101 Firefox/70.0' /* Optional */,
   username: 'chmielewski.testing1' /* username */,
   password: 'lovepolanD123' /* password */,
   hashtags: ['cars', 'warsaw', 'szczecin'] /* hashtags */,
   likesPerHashtag: 5 /* likes for one hashtag */,
   breakBetweenLikes: 15000 /* breakdown between likes */,
   breakBetweenHashtags: 60000 /* breakdown between hashtags */,
   commentsPerHashtag: 5,
   breakBetweenComments: 20000,
   comments: ['Nice!', 'Looks good!'],
   mode: 'autocomment' /* Currently only available autolike */,
};
